name: rejal_allah
description: تطبيق رجال الله - منصة إيمانية شاملة (بدون إنترنت)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # للتعامل مع قاعدة البيانات المحلية SQLite
  sqflite: any
  path: any
  flutter_services_binding: any

  # لتحديد مواقيت الصلاة فلكياً بدون نت
  adhan: any
  # لمعرفة موقع المستخدم الجغرافي لحساب الصلاة
  geolocator: any
  # لتشغيل الصوتيات (القرآن والأدعية)
  just_audio: any
  # لحفظ المفضلة والإعدادات
  shared_preferences: any
  # بوصلة القبلة
  flutter_compass: any
  # الإشعارات والتنبيهات (الأذان والتذكير)
  flutter_local_notifications: any
  timezone: any
  
  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true

  # تعريف الملفات التي سيتم تضمينها في التطبيق (بدون إنترنت)
  assets:
    - assets/images/
    - assets/db/sql_app.db
